Semantic Deduplication Documentation
NVIDIA/NeMo-Curator pull request #159
Opened 2024-07-22 18:45 UTC by VibhuJawa

## Description

This PR adds Semantic Deduplication Documentation.

2024-07-22 21:04 UTC, sarahyurick requested changes
The steps are very clear, thanks! Just added a few minor comments.

2024-07-22 21:04 UTC, sarahyurick commented on docs/user-guide/semdedup.rst
> +      --log-dir=./log/add_id
Is there no API support for this yet?

2024-07-22 21:04 UTC, sarahyurick commented on docs/user-guide/semdedup.rst
> +For more details on the algorithm and its performance implications, refer to the original paper: "SemDeDup: Data-efficient learning at web-scale through semantic deduplication" by Abbas et al.
Link again.

2024-07-23 02:00 UTC, VibhuJawa commented on docs/user-guide/semdedup.rst
> +For more details on the algorithm and its performance implications, refer to the original paper: "SemDeDup: Data-efficient learning at web-scale through semantic deduplication" by Abbas et al.
Resolved by: https://github.com/NVIDIA/NeMo-Curator/pull/159/commits/5eae8a68096518582c23fe6d1336224b31112b45

2024-07-23 02:00 UTC, VibhuJawa commented on docs/user-guide/semdedup.rst
> +As outlined in the paper "SemDeDup: Data-efficient learning at web-scale through semantic deduplication" by Abbas et al.,
Resolved by : https://github.com/NVIDIA/NeMo-Curator/pull/159/commits/5eae8a68096518582c23fe6d1336224b31112b4

2024-07-23 16:44 UTC, ryantwolf reviewed
Looks good overall. Main thing is to emphasize how this can be used for multiple modalities and limit the number of times we reference text-specific stuff.

2024-07-23 16:47 UTC, VibhuJawa commented on docs/user-guide/semdedup.rst
> +Unlike exact or fuzzy deduplication, which focus on textual similarity, semantic deduplication leverages the semantic meaning of the content to identify duplicates.
Ha ha, I added it and removed it because we dont have an example yet. Let me add it back.

2024-07-23 19:26 UTC, sarahyurick approved these changes
LGTM!

2024-07-23 22:50 UTC, VibhuJawa commented on docs/user-guide/semdedup.rst
> +Unlike exact or fuzzy deduplication, which focus on textual similarity, semantic deduplication leverages the semantic meaning of the content to identify duplicates.
Resolved

2024-07-23 22:51 UTC, VibhuJawa commented on docs/user-guide/semdedup.rst
> +1. Embedding Generation: Each data point is embedded using a pre-trained language model.
Resolved by https://github.com/NVIDIA/NeMo-Curator/pull/159/commits/dfdc62869479e80cb91b78bca5ad15352cfda53b

2024-07-23 22:52 UTC, VibhuJawa commented on docs/user-guide/semdedup.rst
> +    from nemo_curator.modules.semantic_dedup import EmbeddingCreator
Resolved by https://github.com/NVIDIA/NeMo-Curator/pull/159/commits/dfdc62869479e80cb91b78bca5ad15352cfda53b

2024-07-23 22:52 UTC, VibhuJawa commented on docs/user-guide/semdedup.rst
> +1. Embeddings for each document
Resolved by https://github.com/NVIDIA/NeMo-Curator/pull/159/commits/dfdc62869479e80cb91b78bca5ad15352cfda53b

2024-07-23 22:52 UTC, VibhuJawa commented on docs/user-guide/semdedup.rst
> +5. Duplicate Removal: From each group of semantic duplicates within a cluster, one representative document is kept (typically the one with the lowest cosine similarity to the cluster centroid) and th
Resolved by https://github.com/NVIDIA/NeMo-Curator/pull/159/commits/dfdc62869479e80cb91b78bca5ad15352cfda53b

2024-07-23 23:00 UTC, VibhuJawa commented on docs/user-guide/semdedup.rst
> +    eps_thresholds:
Resolved by: https://github.com/NVIDIA/NeMo-Curator/pull/159/commits/33634a94c471236fce74f1c539a9df1a091e45ff

2024-07-23 23:00 UTC, VibhuJawa commented on docs/user-guide/semdedup.rst
> +Unlike exact or fuzzy deduplication, which focus on textual similarity, semantic deduplication leverages the semantic meaning of the content to identify duplicates.
Done

2024-07-23 23:00 UTC, VibhuJawa commented
@ryantwolf , Please feel free to review the PR again. Have made suggested changes

2024-07-26 15:34 UTC, ryantwolf approved these changes
Excellent!

2024-07-26 16:45 UTC, merged