Add image documentation
NVIDIA/NeMo-Curator pull request #238
Opened 2024-09-10 15:34 UTC by ryantwolf

## Description

Adds documentation for the image curation modules.

## Usage

N/A
## Checklist

- [ ] I am familiar with the [Contributing Guide](https://github.com/NVIDIA/NeMo-Curator/blob/main/CONTRIBUTING.md).
- [ ] New or Existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

2024-10-18 20:35 UTC, ryantwolf commented
The docs are ready to review.

2024-10-21 18:04 UTC, sarahyurick reviewed
Great tutorial! Added general comments and proofreading.

2024-10-21 18:04 UTC, sarahyurick commented on docs/user-guide/image/embedders.rst
> +* ``load_dataset_shard()`` will take in a path to a tar file and return an iterable over the shard. The iterable should return a tuple of (a batch of data, metadata).
```suggestion
* ``load_dataset_shard()`` will take in a path to a tar file and return an iterable over the shard. The iterable should return a tuple of ``(a batch of data, metadata)``.
```

2024-10-22 17:02 UTC, ryantwolf commented on README.md
> -At the core of the NeMo Curator is the `DocumentDataset` which serves as the the main dataset class. It acts as a straightforward wrapper around a Dask `DataFrame`. The Python library offers easy-to-
We now have multiple dataset formats. I also felt this section was diving into the implementation details too early in the document.

2024-10-22 17:09 UTC, ryantwolf commented on README.md
> +  - [Fuzzy](https://docs.nvidia.com/nemo-framework/user-guide/latest/datacuration/gpudeduplication.html) (Minhash LSH)
What do you think about `[Fuzzy deduplication](https://docs.nvidia.com/nemo-framework/user-guide/latest/datacuration/gpudeduplication.html) via MinHash Locality Sensitive Hashing`?

2024-10-22 17:18 UTC, ryantwolf commented on README.md
> +  - Common Crawl, Wikipedia, and ArXiv sources
What do you think about `Default implementations Common Crawl, Wikipedia, and ArXiv sources`? I feel like the "download and extract" and "text data" are already addressed by the section headers and bullet points.

2024-10-22 17:30 UTC, ryantwolf commented on README.md
> +- [Unicode Fixing](https://docs.nvidia.com/nemo-framework/user-guide/latest/datacuration/languageidentificationunicodeformatting.html)
Changed to `Unicode Reformatting`. I don't think saying `and cleaning` is particularly valuable since its not a separate operation.

2024-10-22 20:25 UTC, ryantwolf commented on README.md
>    - Classifier-based filtering via [fastText](https://fasttext.cc/)
I'm not sure if adding "Quality" in front of it makes much of a difference honestly. For the sake of conciseness, I'd prefer to keep it as it is unless you feel like the "Quality" adjective helps a lot.

2024-10-22 20:25 UTC, ryantwolf commented on README.md
> +  - [fastText]((https://docs.nvidia.com/nemo-framework/user-guide/latest/datacuration/qualityfiltering.html))
Same concern with "quality" as above.

2024-10-22 20:27 UTC, ryantwolf commented on README.md
> +- **GPU Deduplication**
I would like to keep a mention of the fact that GPUs are used in deduplication. Not sure how to best combine it. Upon rereading my original bullet though, I wonder if it sounds too much like we are deduplicating GPUs haha.

2024-10-22 21:49 UTC, ryantwolf commented on README.md
> -These modules offer flexibility and permit reordering, with only a few exceptions. In addition, the [NeMo Framework Launcher](https://github.com/NVIDIA/NeMo-Megatron-Launcher) provides pre-built pipe
done. Let me know what you think of it.

2024-10-22 21:50 UTC, ryantwolf commented
@sarahyurick I addressed most of your feedback. I left comments where I disagreed / wanted clarification. Please take another look when you can.

2024-10-23 22:34 UTC, sarahyurick commented on README.md
> +  - [Fuzzy](https://docs.nvidia.com/nemo-framework/user-guide/latest/datacuration/gpudeduplication.html) (Minhash LSH)
Yes that works, thanks.

2024-10-23 22:35 UTC, sarahyurick commented on README.md
> +  - Common Crawl, Wikipedia, and ArXiv sources
Yes that's fine, although I think it should be "Default implementations FOR Common Crawl, Wikipedia, and ArXiv sources".

2024-10-23 22:35 UTC, sarahyurick commented on README.md
> +- [Language Identification](https://docs.nvidia.com/nemo-framework/user-guide/latest/datacuration/languageidentificationunicodeformatting.html)
Okay, looks good.

2024-10-23 22:38 UTC, sarahyurick commented on README.md
> +  - [fastText]((https://docs.nvidia.com/nemo-framework/user-guide/latest/datacuration/qualityfiltering.html))
Up to you. Although, I think the link is still broken from the extra set of parentheses here.

2024-10-23 22:40 UTC, sarahyurick commented on README.md
> +- **GPU Deduplication**
Yeah that makes sense. In that case maybe "GPU-Accelerated Deduplication" or "GPU-Accelerated Document Deduplication"?

2024-10-23 22:41 UTC, sarahyurick requested changes
Thanks for updating! I believe there should just be 3 more comments from my previous review that still need to be updated, otherwise LGTM.

2024-10-24 17:20 UTC, ryantwolf commented
I think I addressed all your concerns @sarahyurick, let me know if I missed anything though.

2024-10-24 17:31 UTC, sarahyurick approved these changes
Thanks!

2024-10-24 20:30 UTC, merged