Add Image Curation Tutorial
NVIDIA/NeMo-Curator pull request #254
Opened 2024-09-18 21:48 UTC by ryantwolf

## Description

Adds a tutorial showcasing a few of the key features of image curation currently offered in NeMo Curator
1. Embedding Creation
2. Aesthetic Classification
3. Semantic Deduplication

## Usage

Run the notebook from start to finish. It will download a sample dataset and perform the operations listed above on it.
## Checklist

- [ ] I am familiar with the [Contributing Guide](https://github.com/NVIDIA/NeMo-Curator/blob/main/CONTRIBUTING.md).
- [ ] New or Existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

2024-09-18 21:49 UTC, ryantwolf commented
@VibhuJawa I made a few minor modifications to semdedup so that the embedding column name was more flexible. Let me know what you think.

2024-09-18 21:58 UTC, ryantwolf commented
Also, if anyone has ideas on how to make the modules more flexible such that we don't need to do the silly conversion between `DocumentDataset` and `ImageTextPairDataset` that would be good.

2024-09-18 23:48 UTC, sarahyurick requested changes
Thanks @ryantwolf this is a really cool tutorial! Generally looks good, I added a bunch of nits.

2024-09-18 23:48 UTC, sarahyurick commented on nemo_curator/modules/semantic_dedup.py
>  )
What about at https://github.com/NVIDIA/NeMo-Curator/blob/main/nemo_curator/modules/semantic_dedup.py#L193?

2024-09-18 23:48 UTC, sarahyurick commented on tutorials/image-curation/image-curation.ipynb
> +    "NeMo Curator has a few built-in modules for \n",
Incomplete sentence.

2024-09-18 23:48 UTC, sarahyurick commented on tutorials/image-curation/image-curation.ipynb
> +    "To download the dataset, we are going to use a tool called img2dataset. Let's install it and download the dataset."
```suggestion
    "To download the dataset, we are going to use a tool called [img2dataset](https://github.com/rom1504/img2dataset). Let's install it and download the dataset."
```

2024-09-18 23:48 UTC, sarahyurick commented on tutorials/image-curation/image-curation.ipynb
> +    "First, we need to get a list of URLs that identify where all the images are hosted"
```suggestion
    "First, we need to get a list of URLs that identify where all the images are hosted:"
```

2024-09-18 23:48 UTC, sarahyurick commented on tutorials/image-curation/image-curation.ipynb
> +    "# !pip install --extra-index-url https://pypi.nvidia.com nemo-curator[image]\n",
Should probably only include one of these.

2024-09-18 23:48 UTC, sarahyurick commented on tutorials/image-curation/image-curation.ipynb
> +    "## Create CLIP Embeddings\n",
Maybe explain a little more about what this means, what we're doing, and what the goal is?

2024-09-18 23:48 UTC, sarahyurick commented on tutorials/image-curation/image-curation.ipynb
> +    "We can now define the embedding creation step in our pipeline. NeMo Curator has support for all [timm](https://pypi.org/project/timm/) models. NeMo Curator's aesthetic classifier is trained on e
Maybe add a link for more information about `vit_large_patch14_clip_quickgelu_224.openai`?

2024-09-18 23:48 UTC, sarahyurick commented on tutorials/image-curation/image-curation.ipynb
> +    "Once the computation is triggered, the cell below will\n",
```suggestion
    "Once the computation is triggered, the cell below will:\n",
```

2024-09-18 23:48 UTC, sarahyurick commented on tutorials/image-curation/image-curation.ipynb
> +    "Since NeMo Curator uses Dask, the cell below will not cause the embeddings to be created. The computation will only begin once we inspect the output in the `dataset.metadata.head()` call or when
Maybe elaborate a bit more on when to use `save_metadata` versus `to_webdataset`?

2024-09-18 23:48 UTC, sarahyurick commented on tutorials/image-curation/image-curation.ipynb
> +    "With the embeddings now created, we can use the aesthetic classifier. This classifier assigns a score from 0 to 10 that corresponds to how aesthetically pleasing the image is. A score of 0 means
```suggestion
    "With the embeddings now created, we can use the aesthetic classifier. This classifier assigns a score from 0 to 10 that corresponds to how aesthetically pleasing the image is. A score of 0 means that the image is not pleasant to look at, while a score of 10 is pleasant to look at. The exact classifier used is the `LAION-Aesthetics_Predictor V2`. More information on the model can be found here: https://laion.ai/blog/laion-aesthetics/.\n",
```

2024-09-18 23:48 UTC, sarahyurick commented on tutorials/image-curation/image-curation.ipynb
> +    "Unlike `dataset.save_metadata()`, `dataset.to_webdataset()` will modify the tar files as well as the `.parquet` files. It will cause the tar files to be resharded and any entries that have an ae
Nice, this explains the question I had earlier.

2024-09-18 23:48 UTC, sarahyurick commented on tutorials/image-curation/image-curation.ipynb
> +    "### Visualize Results\n",
Can you run the whole notebook so I can see what this looks like?

2024-09-18 23:48 UTC, sarahyurick commented on tutorials/image-curation/image-curation.ipynb
> +    "NeMo Curator provides an easy module for semantically deduplicating images. Semantic duplicates are images that contain almost the same information content, but are perceptually different. Two i
```suggestion
    "NeMo Curator provides an easy module for semantically deduplicating images. Semantic duplicates are images that contain almost the same information content, but are perceptually different. Two images of the same dog taken from slightly different angles would be considered semantic duplicates. NeMo Curator' semantic deduplication approach is based on the paper [SemDeDup: Data-efficient learning at web-scale through semantic deduplication](https://arxiv.org/pdf/2303.09540) by Abbas et al which has demonstrated that deduplicating your data can lead to the same downstream performance in *half* the number of training iterations. For more information on the algorithm, you can check out the [documentation page](https://docs.nvidia.com/nemo-framework/user-guide/latest/datacuration/semdedup.html#data-curator-semdedup)."
```

2024-09-18 23:48 UTC, sarahyurick commented on tutorials/image-curation/image-curation.ipynb
> +    "We got a list of deduplicated image ids. Now we can remove entries with those ids from our dataset, and reshard the dataset to remove them from the tar files."
```suggestion
    "We got a list of deduplicated image IDs. Now we can remove entries with those IDs from our dataset, and reshard the dataset to remove them from the tar files."
```

2024-09-18 23:48 UTC, sarahyurick commented on tutorials/image-curation/image-curation.ipynb
> +    "### Visualize Duplicates\n",
This is a very cool demo!

2024-09-18 23:48 UTC, sarahyurick commented on tutorials/image-curation/image-curation.ipynb
> +    "1. The `id` column represents the id of the datapoint.\n",
```suggestion
    "1. The `id` column represents the ID of the datapoint.\n",
```

2024-09-18 23:48 UTC, sarahyurick commented on tutorials/image-curation/image-curation.ipynb
> +    "1. `max_id` represents the id of the image that `id` is the most similar to.\n",
```suggestion
    "1. `max_id` represents the ID of the image that `id` is the most similar to.\n",
```

2024-09-18 23:48 UTC, sarahyurick commented on tutorials/image-curation/image-curation.ipynb
> +    "1. `eps=0.01` is `True` if `cosine_sim_score` is `>= 0.99`\n",
```suggestion
    "1. `eps=0.01` is `True` if `cosine_sim_score` is `>= 0.99`.\n",
```

2024-09-18 23:48 UTC, sarahyurick commented on tutorials/image-curation/image-curation.ipynb
> +    "1. `eps=0.001` is `True` if `cosine_sim_score` is `>= 0.999`\n",
```suggestion
    "1. `eps=0.001` is `True` if `cosine_sim_score` is `>= 0.999`.\n",
```

2024-09-18 23:48 UTC, sarahyurick commented on tutorials/image-curation/image-curation.ipynb
> +    "This dataset has a lot of exact duplicates, so those are caught by `eps=0.001`, and we have filtered out the ids so we don't see them here. There are still a few documents that are similar, but
```suggestion
    "This dataset has a lot of exact duplicates, so those are caught by `eps=0.001`. We have filtered out the IDs so we don't see them here. There are still a few documents that are similar, but not exact duplicates. We can examine `000008687.jpg` and `000008672.jpg` using our helper function from earlier to see what they look like."
```

2024-09-18 23:48 UTC, sarahyurick commented on tutorials/image-curation/image-curation.ipynb
> +    "Here, we can see that the images are different. Notably, the baby's head is looking in a different direction. Despite the small differences, these images would still be considered semantic dupli
Incomplete sentence.

2024-09-19 16:33 UTC, ryantwolf commented on tutorials/image-curation/image-curation.ipynb
> +    "### Visualize Duplicates\n",
Thanks!

2024-09-19 17:04 UTC, ryantwolf commented
Thanks for the feedback, should be good for another review @sarahyurick

2024-09-19 17:17 UTC, sarahyurick requested changes
Thanks! The outputs are very nice. I just have 2 tiny nits:

- At beginning of notebook, add punctuation at the end of `In the following notebook, we'll be exploring all of the functionality that NeMo Curator has for image dataset curation. NeMo Curator has a few built-in modules for:`.
- At the end of the notebook, add a period to `Feel free to adjust the epsilon threshold and see what kinds of images are considered duplicates.`.

2024-09-19 20:06 UTC, ryantwolf commented
@sarahyurick nits should be addressed

2024-09-19 22:00 UTC, VibhuJawa requested changes
Everything looks great to me, have some minor nits regarding notebook but otherwise looks great to me.

2024-09-19 22:00 UTC, VibhuJawa commented on tutorials/image-curation/image-curation.ipynb
Cant leave line by line comments on the notebook . Mostly nits. 

We should maybe add a Table of contents (Below will add that) , so that it is easier for folks to navigate to the section they want. 

```
from IPython.display import Markdown, display

toc = """
# Table of Contents
1. [Download a Sample Dataset](#Download-a-Sample-Dataset)
2. [Install NeMo Curator](#Install-NeMo-Curator)
3. [Create CLIP Image Embeddings](#Create-CLIP-Image-Embeddings)
4. [Aesthetic Classifier](#Aesthetic-Classifier)
5. [Semantic Deduplication](#Semantic-Deduplication)
"""

display(Markdown(toc))
```

2.  We should probably add a small heading which has details about creating the `dask cluster` and a line or two explaining that. 

Like below should be its own subsection (probably after installing curator) 
```
from nemo_curator import get_client
client = get_client(cluster_type="gpu")
```


3.  For semdedup, we should probably add a comment about:
1.  #n_clusters like - Increase 'n_clusters' in ClusteringModel for more efficient processing of large datasets, #max_iters for real world large scale datasets.

2024-09-19 23:03 UTC, sarahyurick approved these changes
LGTM. In favor of Vibhu's suggestions.

2024-09-20 17:23 UTC, ryantwolf commented on tutorials/image-curation/image-curation.ipynb
Good points.

2024-09-20 17:34 UTC, VibhuJawa approved these changes
LGTM

2024-09-20 17:39 UTC, merged