Fix 255 - Improve separate_by_metadata performance when dealing with jsonl files
NVIDIA/NeMo-Curator pull request #256
Opened 2024-09-21 22:31 UTC by miguelusque

Fix #255 - Improve separate_by_metadata performance when dealing with jsonl files

This PR improves separate_by_metadata performance a minimum of 3x, while reducing the memory needs from O(N) to O(1).

The above translates to less OOMs, better CPU utilization, and constant memory usage (around 11GB in a 500GB server).

I have also added a new functionality that allows to select which fields to keep, or which fields to exclude. This is interesting, for instance, after applying a quality classifier, where some user would like to keep only "High" quality documents.

Hope it helps!

2024-09-26 16:00 UTC, ryantwolf requested changes
Thanks for making this! I'll run the CI in parallel to make sure this produces the same results as expected.

2024-09-26 20:26 UTC, miguelusque commented on nemo_curator/utils/file_utils.py
> +    if type(input_data) is dd.DataFrame:
Done!

2024-09-26 20:27 UTC, miguelusque commented on nemo_curator/utils/file_utils.py
> +        if input_type in ["json", "jsonl"] and output_type in ["json", "jsonl"]:
Thank you Ryan, I do like your approach. Just fixed it. Thanks!

2024-09-26 20:27 UTC, miguelusque commented on nemo_curator/scripts/separate_by_metadata.py
> +            value_selection_filter=args.value_selection_filter,
Done!

2024-09-26 20:27 UTC, miguelusque commented on nemo_curator/utils/file_utils.py
> +                os.path.join(input_data, "**", "*"),
Sure! Done!

2024-10-01 18:42 UTC, ryantwolf approved these changes
Thanks for the improvements!

2024-10-01 18:43 UTC, merged