Add Curator and Spark example in docs
NVIDIA/NeMo-Curator pull request #261
Opened 2024-09-25 00:29 UTC by ronjer30

## Description
Updated docs to include example to read and write datasets with NeMo Curator and Apache Spark
## Usage
N/A
## Checklist

- [X] I am familiar with the [Contributing Guide](https://github.com/NVIDIA/NeMo-Curator/blob/main/CONTRIBUTING.md).
- N/A [ ] New or Existing tests cover these changes.
- [X] The documentation is up to date with these changes.

2024-09-30 17:28 UTC, sarahyurick requested changes
Awesome tutorial and very easy to follow! Added a couple nits but otherwise looks good.

2024-09-30 17:28 UTC, sarahyurick commented on docs/user-guide/sparkother.rst
> +NeMo Curator uses the ``DocumentDataset`` to read and write ``JSONL`` and ``Parquet`` files.
```suggestion
NeMo Curator uses the ``DocumentDataset`` class to read and write JSONL and Parquet files. 
```

2024-09-30 17:28 UTC, sarahyurick commented on docs/user-guide/sparkother.rst
> +It is a wrapper around a `Dask DataFrame <https://docs.dask.org/en/stable/dataframe.html>`_.  Apache Spark can read and write JSONL and Parquet files generated by NeMo Curator, and similarly, NeMo Cu
```suggestion
It is a wrapper around a `Dask (or Dask-cuDF) DataFrame <https://docs.dask.org/en/stable/dataframe.html>`_.  Apache Spark can read and write JSONL and Parquet files generated by NeMo Curator, and similarly, NeMo Curator can work with the outputs generated by Spark.
```

2024-09-30 17:28 UTC, sarahyurick commented on docs/user-guide/sparkother.rst
> +Apache Spark can read these files using standard APIs. Assuming you already have a Spark session running, you can read files in the directory using:
```suggestion
Apache Spark can read these files using standard APIs. Let's first create a Spark session called ``NeMoCuratorExample``, then we can read files in the directory using:
```

Nit, but it looks like you already include the code to start a Spark session below.

2024-09-30 17:28 UTC, sarahyurick commented on docs/user-guide/sparkother.rst
> +To interoperate between NeMo Curator ``DocumentDataset`` and Spark DataFrames, we recommend using parquet files for data exchange.
```suggestion
To interoperate between NeMo Curator ``DocumentDataset`` and Spark DataFrames, we recommend using Parquet files for data exchange.  
```

2024-09-30 17:28 UTC, sarahyurick commented on docs/user-guide/sparkother.rst
> +    stories_df = stories_df.withColumn("WordCount", size(split(stories_df["text"], r'\s+')))
```suggestion
    stories_df = stories_df.withColumn("WordCount", size(split(stories_df["text"], r"\s+")))
```

2024-09-30 17:28 UTC, sarahyurick commented on docs/user-guide/sparkother.rst
> +    #ignores checksum and marker files created by Spark
```suggestion
    # Ignores checksum and marker files created by Spark 
```

2024-09-30 17:28 UTC, sarahyurick commented on docs/user-guide/sparkother.rst
> +         if not (filename.endswith('.crc') or filename.endswith('_SUCCESS'))
```suggestion
         if not (filename.endswith(".crc") or filename.endswith("_SUCCESS"))
```

2024-09-30 17:28 UTC, sarahyurick commented on docs/user-guide/sparkother.rst
> +    stories_dataset = DocumentDataset.read_parquet(processed_files, backend='pandas')
```suggestion
    stories_dataset = DocumentDataset.read_parquet(processed_files, backend="pandas")
```

2024-10-03 20:15 UTC, ronjer30 commented
Thanks for the feedback @sarahyurick, I've addressed all the changes.

2024-10-03 20:21 UTC, sarahyurick commented
Looks like you need to fix whitespace issues somewhere, otherwise looks good.

2024-10-03 20:43 UTC, ronjer30 commented
Thanks @sarahyurick, fixed trailing whitespace

2024-10-04 19:23 UTC, sarahyurick commented
Looks like there's still more. They could be extra spaces at the end of some lines.

2024-10-07 18:55 UTC, ronjer30 commented
Thanks @sarahyurick, pushed another commit, hopefully this resolves all of it.

2024-10-07 18:58 UTC, sarahyurick approved these changes

2024-10-07 23:14 UTC, merged