Added example notebook for translation with ct2 model.
NVIDIA/NeMo-Curator pull request #262
Opened 2024-09-25 19:11 UTC by uahmed93

## Description
This PR is adding a translation example to hindi languge via ct2 model.
Issue here: .
This example depends on CrossFit's [PR](https://github.com/rapidsai/crossfit/pull/83) 

## Checklist

- [ ] I am familiar with the [Contributing Guide](https://github.com/NVIDIA/NeMo-Curator/blob/main/CONTRIBUTING.md).
- [ ] New or Existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

2024-10-02 17:10 UTC, VibhuJawa requested changes
Left a initial review, thanks for working on this tutorial.

2024-10-02 17:10 UTC, VibhuJawa commented on tutorials/translation/ct2_hindi_translation.ipynb
> +    "## Define output directory\n"
```suggestion
    "##### Define output directory\n"
```

2024-10-02 17:10 UTC, VibhuJawa commented on tutorials/translation/ct2_hindi_translation.ipynb
> +   "cell_type": "markdown",
Add a table of contents here. 

See https://github.com/NVIDIA/NeMo-Curator/blob/cef1c3408684e9ce96e8125f041378407daf0a7b/tutorials/image-curation/image-curation.ipynb example for input

2024-10-02 17:10 UTC, VibhuJawa commented on tutorials/translation/ct2_hindi_translation.ipynb
> +    "Now, we will create a ctranslate2 model class, rquired for calling inference on ct2 model, and attch it with crossfit's HFModel class. These Model definitions can be found in CrossFit's example,
```
## CTranslate2 Model Integration

We'll now create a custom CTranslate2 model class, which is essential for performing inference on the CT2 model. (Add link to model and why this is a better model, add benchmarks if any) 
```

And then organize it into this sections (something like below) : 
```
 This class will be integrated with CrossFit's `HFModel` class to leverage CrossFit's efficient batching and processing capabilities.

### Key Components:

1. **CT2CustomModel**: A custom class for CTranslate2 model inference.
2. **ModelForSeq2SeqModel**: An extension of CrossFit's `HFModel` class, tailored for our translation task.
3. **TranslationConfig**: A dataclass for managing translation-specific configuration parameters.

These model definitions are inspired by examples from the CrossFit project. For reference, you can find similar implementations in the [CrossFit GitHub repository](https://github.com/rapidsai/crossfit/pull/83/files#diff-d3c29a7456aac8be2bb3d53ba3d983e36631ea8dd36c4e52d9f3217183d4568f).
```

2024-10-08 10:21 UTC, uahmed93 commented
Hi @VibhuJawa  / @sarahyurick ,
can you please merge this MR ?

2024-10-10 21:05 UTC, sarahyurick requested changes
I can leave a more detailed review for focusing on grammar nits, but for now can you please implement the code changes from my review, then rerun the entire notebook (executing from start to bottom and in order)?

2024-10-10 21:05 UTC, sarahyurick commented on tutorials/translation/ct2_hindi_translation.ipynb
> +    "@dataclass\n",
How about removing this entire cell and creating a new script in https://github.com/NVIDIA/NeMo-Curator/tree/main/nemo_curator/classifiers?

2024-10-10 21:05 UTC, sarahyurick commented on tutorials/translation/ct2_hindi_translation.ipynb
> +    "class IndicTranslation(DistributedDataClassifier):\n",
Same comment as above, why don't we move all of this logic into https://github.com/NVIDIA/NeMo-Curator/tree/main/nemo_curator/classifiers?

2024-10-10 21:19 UTC, sarahyurick commented on tutorials/translation/ct2_hindi_translation.ipynb
> +    "@dataclass\n",
Ah ok I see, using a utils file sounds good to me.

2025-04-02 22:24 UTC, VibhuJawa commented
Closing because of all the great work @sarahyurick  did here with https://github.com/NVIDIA/NeMo-Curator/pull/336

2025-04-02 22:24 UTC, closed without merging