Pin Rapids to 24.8 for 0.5.0 Release
NVIDIA/NeMo-Curator pull request #273
Opened 2024-10-01 18:23 UTC by praateekmahajan

## Description
Since our release is planned for 2nd week of October, and [Rapids might do a 24.10 release by 10th Oct](https://docs.rapids.ai/maintainers/)

2024-10-01 18:24 UTC, ayushdg approved these changes

2024-10-01 18:25 UTC, ryantwolf approved these changes

2024-10-01 22:10 UTC, ryantwolf commented on requirements/requirements.txt
> -numpy<2
Do you just want to have `numpy` without any pin instead of removing it entirely?

2024-10-01 22:46 UTC, ayushdg requested changes
We should also hold off on merging until we can run some gpu tests locally + Nemo ci (if it has any tests using spacy features). Just to ensure nothing on the gpu+ space end changed.

2024-10-02 20:22 UTC, ayushdg approved these changes
Is the plan to add an upper pin to spacy for now and investigate removing the numpy pin completely in a followup?

2024-10-02 20:25 UTC, merged