Japanese support for `get_word_splitter`
NVIDIA/NeMo-Curator pull request #320
Opened 2024-10-23 19:20 UTC by sarahyurick

Closes https://github.com/NVIDIA/NeMo-Curator/issues/257.

2024-10-29 21:26 UTC, ryantwolf requested changes
With documentation updates, this should be good to go.

2024-10-29 21:26 UTC, ryantwolf commented on nemo_curator/utils/text_utils.py
> +    elif language == "ja":
Do you mind updating the docstrings in the filters where the `get_word_splitter` is used to explain the splitting strategy we do for each language?

2024-10-29 21:26 UTC, ryantwolf commented on requirements/requirements.txt
> +mecab-python3==1.0.9
Any reason for the hard pin? If not, I'd prefer to just keep it at `mecab-python3`

2024-10-29 21:49 UTC, sarahyurick commented
Thanks @ryantwolf ! Updated.

2024-11-04 19:33 UTC, ryantwolf approved these changes
Great, thanks!

2024-11-04 19:36 UTC, merged