Add support for fine-tune classifier
NVIDIA/NeMo-Curator pull request #325
Opened 2024-10-25 12:19 UTC by VibhuJawa

2024-11-18 16:04 UTC, VibhuJawa commented on nemo_curator/classifiers/aegis.py
> +    Dataset Format:
TODO: Emphasize more about english

2024-11-21 21:25 UTC, sarahyurick reviewed
Added a few typo fixes but looks good so far!

When you get a chance can you add it to the `examples/` and `nemo_curator/scripts/` folders? And to the documentation? You should be able to reference https://github.com/NVIDIA/NeMo-Curator/pull/361 which has all the files that should be created/updated.

2024-11-21 21:25 UTC, sarahyurick commented on nemo_curator/classifiers/aegis.py
> +        add_fintune_gaurd: bool = False,
```suggestion
        add_finetune_guard: bool = False,
```

2024-11-21 21:25 UTC, sarahyurick commented on nemo_curator/classifiers/aegis.py
> +        self.add_fintune_gaurd = add_fintune_gaurd
```suggestion
        self.add_finetune_guard = add_finetune_guard
```

2024-11-21 21:25 UTC, sarahyurick commented on nemo_curator/classifiers/aegis.py
> +        if self.add_fintune_gaurd:
```suggestion
        if self.add_finetune_guard:
```

2024-11-21 21:25 UTC, sarahyurick commented on nemo_curator/classifiers/aegis.py
> +        if self.add_fintune_gaurd:
```suggestion
        if self.add_finetune_guard:
```

2024-11-21 21:25 UTC, sarahyurick commented on nemo_curator/classifiers/aegis.py
> +                    "finetune_guard_path must be provided if add_fine_guard is True"
```suggestion
                    "finetune_guard_path must be provided if add_finetune_guard is True"
```

2024-11-21 21:25 UTC, sarahyurick commented on nemo_curator/classifiers/aegis.py
> +            add_fintune_gaurd=self.config.add_finetune_guard,
```suggestion
            add_finetune_guard=self.config.add_finetune_guard,
```

2024-11-27 01:05 UTC, VibhuJawa commented on nemo_curator/classifiers/aegis.py
> +    Dataset Format:
Done

2024-11-27 01:07 UTC, VibhuJawa commented
> When you get a chance can you add it to the examples/ and nemo_curator/scripts/ folders? And to the documentation? You should be able to reference https://github.com/NVIDIA/NeMo-Curator/pull/361 which has all the files that should be created/updated.

We can do that as a followup, as that is documentation related. Lets get this in first.

2024-11-27 19:49 UTC, sarahyurick requested changes

2024-11-27 19:49 UTC, sarahyurick commented on nemo_curator/classifiers/aegis.py
> +    finetune_guard_path: Optional[str] = None
```suggestion
    finetune_guard_path: str = "nvidia/FineTune-Guard"
```

2024-11-27 19:49 UTC, sarahyurick commented on nemo_curator/classifiers/aegis.py
> +        self.hidden_layer_2 = Linear(500, 1)  # 1000, 100
```suggestion
        self.hidden_layer_0 = Linear(input_dim, 2000)
        self.hidden_layer_1 = Linear(2000, 500)
        self.hidden_layer_2 = Linear(500, 1)
```

2024-11-27 19:49 UTC, sarahyurick commented on nemo_curator/classifiers/aegis.py
> +            # output_hidden_states=True, return_dict_in_generate=True, max_new_tokens=0, pad_token_id=0)
```suggestion
```

2024-11-27 19:49 UTC, sarahyurick commented on nemo_curator/classifiers/aegis.py
> +            return fine_guard_output_tensor
```suggestion
            finetune_guard_input_tensor = response.hidden_states[0][32][:, -1, :].to(
                torch.float
            )
            finetune_guard_output_tensor = self.finetune_guard_net(
                finetune_guard_input_tensor
            ).flatten()
            return finetune_guard_output_tensor
```

2024-11-27 19:49 UTC, sarahyurick commented on nemo_curator/classifiers/aegis.py
> +
```suggestion
```

2024-11-27 19:49 UTC, sarahyurick commented on nemo_curator/classifiers/aegis.py
> +        finetune_guard_path: Optional[str] = None,
```suggestion
```

2024-11-27 19:49 UTC, sarahyurick commented on nemo_curator/classifiers/aegis.py
> +            finetune_guard_path (Optional[str]): The path to the fine-tune guard model
```suggestion
```

2024-11-27 19:49 UTC, sarahyurick commented on nemo_curator/classifiers/aegis.py
> +            finetune_guard_path=finetune_guard_path,
```suggestion
```

2024-11-27 19:49 UTC, sarahyurick commented on nemo_curator/classifiers/aegis.py
> +        print("Starting AEGIS classifier inference", flush=True)
```suggestion
        print("Starting FineTune-Guard classifier inference", flush=True)
```

2024-11-27 20:48 UTC, sarahyurick approved these changes

2024-11-27 20:54 UTC, sarahyurick commented
Some of these commits are not signed, so re-opening it as https://github.com/NVIDIA/NeMo-Curator/pull/397.

2024-11-27 20:54 UTC, closed without merging