Move common dedup utils and remove unused code
NVIDIA/NeMo-Curator pull request #42
Opened 2024-04-23 23:59 UTC by ayushdg

2024-04-26 17:15 UTC, ryantwolf requested changes
Found one bug. I think it looks pretty good otherwise.

2024-04-26 17:15 UTC, ryantwolf commented on nemo_curator/scripts/fuzzy_deduplication/legacy/verify_all_pairs_jaccard.py
Why are we keeping these files around? They use some files that no longer exist like:
```
nemo_curator.gpu_deduplication.jaccard_utils.jaccard_similarity_utils
```

2024-04-26 17:15 UTC, ryantwolf commented on nemo_curator/scripts/fuzzy_deduplication/README.md
I like this documentation. Could you include it in the user guide too? [Here](https://github.com/NVIDIA/NeMo-Curator/blob/main/docs/user-guide/GpuDeduplication.rst) in particular.

2024-04-26 17:15 UTC, ryantwolf commented on setup.py
> +            "gpu_compute_minhashes=nemo_curator.scripts.fuzzy_deduplication.compute_minhashes:console_script",
I get this error when trying to run the scripts:
```
Traceback (most recent call last):
  File "/home/rywolf/.local/bin/minhash_buckets", line 5, in <module>
    from nemo_curator.scripts.fuzzy_deduplication.minhash_lsh import console_script
ModuleNotFoundError: No module named 'nemo_curator.scripts.fuzzy_deduplication'
```
I think you need an `__init__.py` in the new subfolder you created.

2024-04-26 23:14 UTC, VibhuJawa approved these changes
Looks good to me (as long as we address Ryan's changes) .  Thanks for the code cleanup and documentation.

2024-04-26 23:14 UTC, VibhuJawa commented on nemo_curator/scripts/fuzzy_deduplication/README.md
> +
Love the documentation here.

2024-04-29 18:33 UTC, ayushdg commented on nemo_curator/scripts/fuzzy_deduplication/legacy/verify_all_pairs_jaccard.py
Makes sense removed.

2024-04-30 15:29 UTC, ryantwolf approved these changes
All my concerns were addressed. Thanks!

2024-04-30 15:29 UTC, merged